### PR TITLE
fix(`Validate`): allow validation of FSI dataset w/ no history

### LINKED ISSUE #1535: bug: running validate in FSI-linked directory requires history
### What is your OS and version?
Mac OS X

### What version of qri are you using (`qri version`)?
v0.9.13-dev

### What did you do?
tried to validate before saving:

```
$ mkdir validate_test
$ cd validate_test
$ qri init
$ qri validate
for linked dataset [b5/validate_example]

repo: no history
```

### What happened?

got `repo:no history`

### What did you expect to happen?

I expected qri to validate based on the data in the working directory

### PR DESCRIPTION
**Pull request by ramfox**
- Pull out logic from `InferValues` and create `InferStructure` function that infers a structure from a body. Adjust tests to test `InferStructure` directly.
- Adjust `lib.Validate` to use `ParseAndResolveRefWithWorkingDir` & `fsi.FilesystemPathToLocal` (to catch any fsiPath), rather then `CanonicalizeDatasetRef`
- Add `TestDatasetRequestValidateFSI` to catch errors when trying to validate a fsi dataset w/ no history

closes #1535

### CODE REVIEW

File: lib/datasets.go [hunk 1]
```diff
@@ -1009,16 +1009,24 @@ func (m *DatasetMethods) Validate(p *ValidateParams, res *ValidateResponse) erro
...
-	if err != nil && err != repo.ErrEmptyRef {
-		if err == repo.ErrNotFound {
-			return fmt.Errorf("cannot find dataset: %s", ref)
+	fsiPath := ""
+	var err error
+	ref := dsref.Ref{}
+
+	// if there is both a bodyfilename and a schema/structure
+	// we don't need to resolve any references
+	if !(p.BodyFilename != "" && schemaFlagType != "") {
```
Comment (ramfox) [inline lib/datasets.go:1018]: The `Validate` code path, with its variety of options, is pretty confusing. Tests were very helpful here, and I'm not sure this is the right time, but a streamlined refactor that does a better job of illustrating the flow and minimizing the 'gotchya's' would be helpful here.

File: lib/datasets.go [hunk 2]
```diff
@@ -1009,16 +1009,24 @@ func (m *DatasetMethods) Validate(p *ValidateParams, res *ValidateResponse) erro
...
+		// TODO (ramfox): we need consts in `dsref` for "local", "network", "p2p"
```
Comment (ramfox) [inline lib/datasets.go:1019]: Again, not sure this is the time, but keep seeing "local" "network" and "p2p" in a bunch of places. Might be nice to have some codified consts that we can rely on.

File: lib/datasets.go [hunk 3]
```diff
@@ -1009,16 +1009,24 @@ func (m *DatasetMethods) Validate(p *ValidateParams, res *ValidateResponse) erro
...
+		ref, _, err = m.inst.ParseAndResolveRefWithWorkingDir(ctx, p.Ref, "local")
+		if err != nil {
+			return err
+		}
+
+		// TODO (b5) - replace this prefix check with a call to qfs.PathKind when it
+		// supports the fsi prefix
```
Comment (ramfox) [inline lib/datasets.go:1026]: Would `qfs` need anything more than just adding `fsi` to the `PathKind` func? Would we have to guarantee any other `fsi` functionality?

File: base/dataset_prepare.go [hunk 4]
```diff
@@ -145,46 +145,66 @@ func InferValues(pro *profile.Profile, ds *dataset.Dataset) error {
...
 
-		// glue whatever we just read back onto the reader
-		// TODO (b5)- this may ruin readers that transparently depend on a read-closer
-		// we should consider a method on qfs.File that allows this non-destructive read pattern
-		ds.SetBodyFile(qfs.NewMemfileReader(body.FileName(), io.MultiReader(buf, body)))
+// InferStructure infers the Structure field of the dataset, guarenteeing
+// that the structure will contain a Format, FormatConfig, and Schema, based
+// on the given dataset body. It will not write over any Structure, Format,
+// FormatConfig, or Schema that already exists.
+func InferStructure(ds *dataset.Dataset) error {
```
Comment (dustmop) [inline base/dataset_prepare.go:164]: This is awesome! A super helpful function to have, I bet this can also be used to solve https://github.com/qri-io/qri/issues/1532 pretty easily.

Looking at https://github.com/qri-io/qri/blob/master/fsi/body.go, it seems fsi does some extra tricks, by using `Seek`, which is can do as it knows it's working with local files. If we use `InterStructure` to also handle "get body" for fsi, we can either drop that extra efficiency gain, or add some dynamic interface checking to this function.

File: base/dataset_prepare.go [hunk 5]
```diff
@@ -145,46 +145,66 @@ func InferValues(pro *profile.Profile, ds *dataset.Dataset) error {
...
+	tr := io.TeeReader(body, buf)
+	var df dataset.DataFormat
+
+	df, err := detect.ExtensionDataFormat(body.FileName())
+	if err != nil {
+		log.Debug(err.Error())
+		return fmt.Errorf("invalid data format: %s", err.Error())
+	}
+
+	guessedStructure, _, err := detect.FromReader(df, tr)
```
Comment (dustmop) [inline base/dataset_prepare.go:184]: I realize this is pretty much a pure extraction refactor, but just wanted to leave a note for myself. Our usage of `detect` is getting more and more coupled to qri core, and there's evidence (such as ignoring the middle return value) that more changes should be made to it to bring it more in line with how qri specifically uses it. So, I'd like to bring up https://github.com/qri-io/qri/issues/1371 again, which proposes that `detect` move out of the `dataset` repo and into `base/detect` so that it's easier to work with.

File: base/dataset_prepare.go [hunk 6]
```diff
@@ -145,46 +145,66 @@ func InferValues(pro *profile.Profile, ds *dataset.Dataset) error {
...
-			ds.Structure.FormatConfig = guessedStructure.FormatConfig
-		}
+	return nil
+}
 
-		// glue whatever we just read back onto the reader
-		// TODO (b5)- this may ruin readers that transparently depend on a read-closer
-		// we should consider a method on qfs.File that allows this non-destructive read pattern
-		ds.SetBodyFile(qfs.NewMemfileReader(body.FileName(), io.MultiReader(buf, body)))
+// InferStructure infers the Structure field of the dataset, guarenteeing
```
Comment (dustmop) [inline base/dataset_prepare.go:160]: guarenteeing -> guaranteeing

File: lib/datasets.go (hunk 2 above)
Comment (dustmop) [reply lib/datasets.go:1019]: I think this would be great to have, I would even go further and say that the resolution source should be it's own type, which is either some known instance like `LocalSource` or `P2PSource`, or something wrapped custom address like `RemoveSource("http://my-remote-url/").

File: lib/datasets.go (hunk 1 above)
Comment (dustmop) [reply lib/datasets.go:1018]: So many negatives! For this condition, you can apply demorgan's law to make it read a little easier, and update the comment at the same time:

```
// If either bodyfile or schema is not provided, need to resolve the reference
if p.BodyFilename == "" || schemaFlagType == "" {
```

File: lib/datasets.go (hunk 3 above)
Comment (dustmop) [reply lib/datasets.go:1026]: Would love to have this as a common utility function, like `fsi.IsFSIPath` so that we don't expose the hard-coded string constant everywhere. I don't know the specific plan for `qfs`, but having a utility function for now would make an eventual switch easier.

File: lib/datasets_test.go [hunk 7]
```diff
@@ -1116,6 +1116,50 @@ Pirates of the Caribbean: At World's End ,foo
...
+	inst := NewInstanceFromConfigAndNode(ctx, config.DefaultConfigForTesting(), node)
+
+	// we need some fsi stuff to fully test remove
+	methods := NewFSIMethods(inst)
+	// create datasets working directory
+	datasetsDir, err := ioutil.TempDir("", "QriTestValidateFSIDataset")
+	if err != nil {
+		t.Fatal(err)
+	}
+	defer os.RemoveAll(datasetsDir)
```
Comment (dustmop) [inline lib/datasets_test.go:1141]: Check out TestRenameNoHistory in this file; you can replace all of this code above by creating a testRunner:

```
	tr := newTestRunner(t)
	defer tr.Delete()
	datasetsDir := tr.CreateAndChdirToWorkDir("QriTestValidateFSIDataset")
        methods := NewFSIMethods(tr.Instance)
```

**Review by dustmop — APPROVED** [review]
LGTM! This is great! Have just a small comment or two on fixes, and a bunch of TODOs mostly for future reference
