### PR TITLE
fix(*): update to allow hashes, and fix bugs that PeerID introduced

### LINKED ISSUE #222: Ensure we can use dataset hashes in API endpoints
Once #220 and #273 is closed, add tests for hashes/fix bugs for:

works for all hashes:
* [x] /me/datasetname/at/[datasethash]
* [x] /at/[datasethash]
* [x] /export/peername/datasetname/at/[datasethash]
* [x] /export/at/[datasethash]
* [x] /add/peername/datasetname/at/[datasethash]
* [x] /history/peername/datasetname/at/[datasethash]

only for most recent hash:
* [x] /history/at/[datasethash]
* [x] /remove/peername/datasetname/at/[datasethash]
* [x] /remove/at/[datasethash]

Does not work:
* /add/at/[datasethash], will return error "need peername and dataset name: '/add/[peername]/[datasetname]'"

### LINKED ISSUE #301: fix(CanonicalizeDatasetRef): giving just a path should canonicalize datasetRef
Currently we do not fully canonicalize the datasetRef if we are just given the path.

Let's fix that!

we should:
1) got, err := repo.GetRef(*ref)
2) if no err: Any fields on the ref that are empty should get filled in from the fields with Got
3) if there are mismatches, return err
4) if not return ref

### LINKED ISSUE #302: bug: refs can save to the refstore without a peername
refs are getting saved to the refstore in the form:
`/name@peerid/ntwk/hash`

instead of:
`peername/name@peerid/ntwk/hash`

### PR DESCRIPTION
**Pull request by ramfox**
closes #302
closes #301 
closes #222

### CODE REVIEW

File: repo/test/test_refstore.go [hunk 1]
```diff
@@ -89,11 +89,11 @@ func testRefstore(r repo.Repo) error {
 	aname := "test_namespace_a"
 	bname := "test_namespace_b"
 	refs := []repo.DatasetRef{
-		repo.DatasetRef{PeerID: "QmZePf5LeXow3RW5U1AgEiNbW46YnRGhZ7HPvm1UmPFPwt", Peername: "peer", Name: aname},
-		repo.DatasetRef{PeerID: "QmZePf5LeXow3RW5U1AgEiNbW46YnRGhZ7HPvm1UmPFPwt", Peername: "peer", Name: bname},
-		repo.DatasetRef{PeerID: "QmZePf5LeXow3RW5U1AgEiNbW46YnRGhZ7HPvm1UmPFPwt", Peername: "peer", Name: "test_namespace_c"},
-		repo.DatasetRef{PeerID: "QmZePf5LeXow3RW5U1AgEiNbW46YnRGhZ7HPvm1UmPFPwt", Peername: "peer", Name: "test_namespace_d"},
-		repo.DatasetRef{PeerID: "QmZePf5LeXow3RW5U1AgEiNbW46YnRGhZ7HPvm1UmPFPwt", Peername: "peer", Name: "test_namespace_e"},
+		{PeerID: "QmZePf5LeXow3RW5U1AgEiNbW46YnRGhZ7HPvm1UmPFPwt", Peername: "peer", Name: aname},
```
Comment (b5) [inline repo/test/test_refstore.go]: nice pickup, we should start doing this anywhere we see slices of literals, looks cleaner. cc @osterbit

**Comment by b5** [comment]
I'm going to merge this b/c you should be sleeping.
