### PR TITLE
docs(cmd): add examples and fix docs on help page for CLI commands

### LINKED ISSUE #433: Some CLI commands don't have usage, some have spelling/grammar errors
### remove
no example usage

### rename
no example usage

### save
no example usage, no flags shown

### validate
no example usage, no flags shown

### diff
no example usage for commands

### PR DESCRIPTION
**Pull request by ramfox**
closes #433

### CODE REVIEW

File: cmd/rename.go [hunk 1]
```diff
@@ -11,11 +11,15 @@ var datasetRenameCmd = &cobra.Command{
 	Aliases: []string{"mv"},
 	Short:   "change the name of a dataset",
 	Long: `
-Rename changes the name of a dataset. So, uh, it’s worth noting that this can 
-break lots of stuff for other people, especially in these early days of qri. 
+Rename changes the name of a dataset.
 
-So free to rename stuff lots at first, but try to settle on a name and stick 
-with it, especially if you want other people to like your datasets.`,
+Note that if someone has added your dataset to their qri node, and then
```
Comment (b5) [inline cmd/rename.go]: _muuuuch better_. can't wait to remove this

File: cmd/validate.go [hunk 2]
```diff
@@ -18,39 +18,44 @@ var (
...
 	validateDsURL            string
-	validateDsPassive        bool
+	// validateDsPassive        bool
 )
 
 // validateCmd represents the validate command
 var validateCmd = &cobra.Command{
 	Use:   "validate",
 	Short: "show schema validation errors",
+	Annotations: map[string]string{
```
Comment (b5) [inline cmd/validate.go]: wow nice catch. damn.
