### PR TITLE
fix(startf): script print statements print to stderr

### LINKED ISSUE #1194: `print('string')` does not work in a transform.
`print()` does not work. `error()` does.

Minimal test case:
```
❯ qri version
0.9.6

❯ cat> error.star
def transform(ds, ctx):
    print("print hello")
    error("error hello")

❯ qri save --dry-run -f error.star me/humba
🏃🏽‍♀️ dry run
Traceback (most recent call last):
  transform.star:3:10: in transform
  <builtin>: in error
Error: transform error: "error hello"
```

### PR DESCRIPTION
**Pull request by b5**
cleans up some crossed wires, adds the necessary methods to test `ErrOutput` within `cmd` package tests.

closes #1194

### CODE REVIEW

File: cmd/save_test.go [hunk 1]
```diff
@@ -147,7 +147,6 @@ func TestSaveRun(t *testing.T) {
 		{"add rows, save", "me/movies", "testdata/movies/dataset.json", "testdata/movies/body_twenty.csv", "Added 10 more rows", "Adding to the number of rows in dataset", true, false, true, "dataset saved: peer/movies@/map/Qmf516nREprnwE3YnBpZd1y9DkS6e2ktKYDLMtz4L4MgMX\nthis dataset has 1 validation errors\n", "", ""},
 		{"no changes", "me/movies", "testdata/movies/dataset.json", "testdata/movies/body_twenty.csv", "trying to add again", "hopefully this errors", false, false, true, "", "error saving: no changes", ""},
 		{"add viz", "me/movies", "testdata/movies/dataset_with_viz.json", "", "", "", false, false, false, "dataset saved: peer/movies@/map/QmXDKr4ryBuzXFhpKPUAe6GmqEacCjgPkG76NyVLpmPDSt\nthis dataset has 1 validation errors\n", "", ""},
-		{"add transform", "me/movies", "testdata/movies/dataset_with_tf.json", "", "", "", false, false, false, "dataset saved: peer/movies@/map/QmaYNBGZUxJJZVFFf9LkqomSZQ5kLRCaprKtNDwGUJ2bYy\nthis dataset has 1 validation errors\n", "", ""},
```
Comment (dustmop) [inline cmd/save_test.go]: Deleting this because it contains the output from the transform script? I think it could be good to have a verification here that `print` is working. If the worry is testing non-vital messages, like the emoji and progress, maybe have the test body trim off text before "running transform..."

Comment (b5) [reply cmd/save_test.go]: I've added an explicit test that confirms print is working, with a test failure that gives more meaningful feedback. I think it justifies dropping this test.

Comment (dustmop) [reply cmd/save_test.go]: Fair, ok, LGTM
